[package]
name = "rff"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
crossterm = "0.27"
ignore = "0.4"
thiserror = "1.0"

[dev-dependencies]
tempfile = "3.10"
